//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_zh_CN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Resources.Localization.Localization.zh-CN", typeof(Localization_zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忽略应用.
        /// </summary>
        internal static string config_behaviorModel_group_ignoreProcess {
            get {
                return ResourceManager.GetString("config.behaviorModel.group.ignoreProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忽略URL.
        /// </summary>
        internal static string config_behaviorModel_group_ignoreURL {
            get {
                return ResourceManager.GetString("config.behaviorModel.group.ignoreURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 偏好.
        /// </summary>
        internal static string config_behaviorModel_group_isSleepWatch {
            get {
                return ResourceManager.GetString("config.behaviorModel.group.isSleepWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用白名单.
        /// </summary>
        internal static string config_behaviorModel_group_whiteList {
            get {
                return ResourceManager.GetString("config.behaviorModel.group.whiteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可以通过进程名称或者正则表达式进行匹配。当使用正则表达式时可以匹配程序路径.
        /// </summary>
        internal static string config_behaviorModel_ignoreProcessList_description {
            get {
                return ResourceManager.GetString("config.behaviorModel.ignoreProcessList.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忽略应用.
        /// </summary>
        internal static string config_behaviorModel_ignoreProcessList_name {
            get {
                return ResourceManager.GetString("config.behaviorModel.ignoreProcessList.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 进程名称，不需要输入.exe。支持正则表达式.
        /// </summary>
        internal static string config_behaviorModel_ignoreProcessList_placeholder {
            get {
                return ResourceManager.GetString("config.behaviorModel.ignoreProcessList.placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 过滤不需要统计的网站或链接.
        /// </summary>
        internal static string config_behaviorModel_ignoreURLList_description {
            get {
                return ResourceManager.GetString("config.behaviorModel.ignoreURLList.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忽略URL.
        /// </summary>
        internal static string config_behaviorModel_ignoreURLList_name {
            get {
                return ResourceManager.GetString("config.behaviorModel.ignoreURLList.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL 支持正则表达式.
        /// </summary>
        internal static string config_behaviorModel_ignoreURLList_placeholder {
            get {
                return ResourceManager.GetString("config.behaviorModel.ignoreURLList.placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 离开电脑时自动停止统计，重启软件生效。（一般情况不建议关闭）.
        /// </summary>
        internal static string config_behaviorModel_isSleepWatch_description {
            get {
                return ResourceManager.GetString("config.behaviorModel.isSleepWatch.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 睡眠监测.
        /// </summary>
        internal static string config_behaviorModel_isSleepWatch_name {
            get {
                return ResourceManager.GetString("config.behaviorModel.isSleepWatch.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅统计白名单内的应用.
        /// </summary>
        internal static string config_behaviorModel_isWhiteList_description {
            get {
                return ResourceManager.GetString("config.behaviorModel.isWhiteList.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用白名单.
        /// </summary>
        internal static string config_behaviorModel_isWhiteList_name {
            get {
                return ResourceManager.GetString("config.behaviorModel.isWhiteList.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可以通过进程名称或者正则表达式进行匹配，当使用正则表达式时可以匹配程序路径.
        /// </summary>
        internal static string config_behaviorModel_processWhiteList_description {
            get {
                return ResourceManager.GetString("config.behaviorModel.processWhiteList.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用白名单.
        /// </summary>
        internal static string config_behaviorModel_processWhiteList_name {
            get {
                return ResourceManager.GetString("config.behaviorModel.processWhiteList.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 进程名称，不需要输入.exe。支持正则表达式.
        /// </summary>
        internal static string config_behaviorModel_processWhiteList_placeholder {
            get {
                return ResourceManager.GetString("config.behaviorModel.processWhiteList.placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外观.
        /// </summary>
        internal static string config_general_group_appearance {
            get {
                return ResourceManager.GetString("config.general.group.appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基础.
        /// </summary>
        internal static string config_general_group_basic {
            get {
                return ResourceManager.GetString("config.general.group.basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 功能.
        /// </summary>
        internal static string config_general_group_feature {
            get {
                return ResourceManager.GetString("config.general.group.feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 概览页.
        /// </summary>
        internal static string config_general_group_overview {
            get {
                return ResourceManager.GetString("config.general.group.overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string config_general_indexPageFrequentUseNum_description {
            get {
                return ResourceManager.GetString("config.general.indexPageFrequentUseNum.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最为频繁显示条数.
        /// </summary>
        internal static string config_general_indexPageFrequentUseNum_name {
            get {
                return ResourceManager.GetString("config.general.indexPageFrequentUseNum.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1|2|3|4|5|6|7|8|9|10.
        /// </summary>
        internal static string config_general_indexPageFrequentUseNum_options {
            get {
                return ResourceManager.GetString("config.general.indexPageFrequentUseNum.options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string config_general_indexPageMoreNum_description {
            get {
                return ResourceManager.GetString("config.general.indexPageMoreNum.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更多显示条数.
        /// </summary>
        internal static string config_general_indexPageMoreNum_name {
            get {
                return ResourceManager.GetString("config.general.indexPageMoreNum.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20.
        /// </summary>
        internal static string config_general_indexPageMoreNum_options {
            get {
                return ResourceManager.GetString("config.general.indexPageMoreNum.options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保留当前的窗口大小，而非使用系统默认尺寸.
        /// </summary>
        internal static string config_general_isSaveWindowSize_description {
            get {
                return ResourceManager.GetString("config.general.isSaveWindowSize.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保留窗口大小.
        /// </summary>
        internal static string config_general_isSaveWindowSize_name {
            get {
                return ResourceManager.GetString("config.general.isSaveWindowSize.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在电脑启动时自动运行 Tai.
        /// </summary>
        internal static string config_general_isStartAtBoot_description {
            get {
                return ResourceManager.GetString("config.general.isStartAtBoot.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开机自启动.
        /// </summary>
        internal static string config_general_isStartAtBoot_name {
            get {
                return ResourceManager.GetString("config.general.isStartAtBoot.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在开机自启动时此选项无效.
        /// </summary>
        internal static string config_general_isStartupShowMainWindow_description {
            get {
                return ResourceManager.GetString("config.general.isStartupShowMainWindow.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动软件时显示主界面.
        /// </summary>
        internal static string config_general_isStartupShowMainWindow_name {
            get {
                return ResourceManager.GetString("config.general.isStartupShowMainWindow.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 统计浏览器的网站访问数据，支持：Google Chrome、MSEdge或任何能够安装Chrome拓展的浏览器。请点击 “关于 &gt; 浏览器统计插件” 了解如何安装和使用此功能。.
        /// </summary>
        internal static string config_general_isWebEnabled_description {
            get {
                return ResourceManager.GetString("config.general.isWebEnabled.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网站浏览统计.
        /// </summary>
        internal static string config_general_isWebEnabled_name {
            get {
                return ResourceManager.GetString("config.general.isWebEnabled.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置打开主界面时显示的页面.
        /// </summary>
        internal static string config_general_startPage_description {
            get {
                return ResourceManager.GetString("config.general.startPage.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动页.
        /// </summary>
        internal static string config_general_startPage_name {
            get {
                return ResourceManager.GetString("config.general.startPage.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 概览|统计|详细|分类.
        /// </summary>
        internal static string config_general_startPage_options {
            get {
                return ResourceManager.GetString("config.general.startPage.options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置以浅色或深色模式显示.
        /// </summary>
        internal static string config_general_theme_description {
            get {
                return ResourceManager.GetString("config.general.theme.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题模式.
        /// </summary>
        internal static string config_general_theme_name {
            get {
                return ResourceManager.GetString("config.general.theme.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浅色|深色.
        /// </summary>
        internal static string config_general_theme_options {
            get {
                return ResourceManager.GetString("config.general.theme.options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string config_general_themeColor_description {
            get {
                return ResourceManager.GetString("config.general.themeColor.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题颜色.
        /// </summary>
        internal static string config_general_themeColor_name {
            get {
                return ResourceManager.GetString("config.general.themeColor.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置一个名称用于识别该关联.
        /// </summary>
        internal static string config_linkMode_name_description {
            get {
                return ResourceManager.GetString("config.linkMode.name.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称.
        /// </summary>
        internal static string config_linkMode_name_name {
            get {
                return ResourceManager.GetString("config.linkMode.name.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将需要关联的进程名称（不带.exe）添加到此，至少两个。.
        /// </summary>
        internal static string config_linkMode_processList_description {
            get {
                return ResourceManager.GetString("config.linkMode.processList.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关联进程.
        /// </summary>
        internal static string config_linkMode_processList_name {
            get {
                return ResourceManager.GetString("config.linkMode.processList.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂时没有数据.
        /// </summary>
        internal static string emptyData_noData {
            get {
                return ResourceManager.GetString("emptyData.noData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 什么都没有.
        /// </summary>
        internal static string emptyData_tooltip {
            get {
                return ResourceManager.GetString("emptyData.tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分类.
        /// </summary>
        internal static string main_categories {
            get {
                return ResourceManager.GetString("main.categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 详细.
        /// </summary>
        internal static string main_details {
            get {
                return ResourceManager.GetString("main.details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 概览.
        /// </summary>
        internal static string main_overview {
            get {
                return ResourceManager.GetString("main.overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        internal static string main_settings {
            get {
                return ResourceManager.GetString("main.settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 统计.
        /// </summary>
        internal static string main_statistics {
            get {
                return ResourceManager.GetString("main.statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已添加至白名单 {0}.
        /// </summary>
        internal static string page_detail_addedToWhitelist {
            get {
                return ResourceManager.GetString("page.detail.addedToWhitelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加到白名单.
        /// </summary>
        internal static string page_detail_addToWhitelist {
            get {
                return ResourceManager.GetString("page.detail.addToWhitelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空统计.
        /// </summary>
        internal static string page_detail_clearAppData {
            get {
                return ResourceManager.GetString("page.detail.clearAppData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制应用文件路径.
        /// </summary>
        internal static string page_detail_copyPath {
            get {
                return ResourceManager.GetString("page.detail.copyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制应用进程名称.
        /// </summary>
        internal static string page_detail_copyProcessname {
            get {
                return ResourceManager.GetString("page.detail.copyProcessname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑别名.
        /// </summary>
        internal static string page_detail_editAlias {
            get {
                return ResourceManager.GetString("page.detail.editAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动应用.
        /// </summary>
        internal static string page_detail_launchApp {
            get {
                return ResourceManager.GetString("page.detail.launchApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开应用所在目录.
        /// </summary>
        internal static string page_detail_openDir {
            get {
                return ResourceManager.GetString("page.detail.openDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        internal static string page_detail_reload {
            get {
                return ResourceManager.GetString("page.detail.reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已从白名单移除此应用 {0}.
        /// </summary>
        internal static string page_detail_removedFromWhitelist {
            get {
                return ResourceManager.GetString("page.detail.removedFromWhitelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从白名单移除.
        /// </summary>
        internal static string page_detail_removeFromWhitelist {
            get {
                return ResourceManager.GetString("page.detail.removeFromWhitelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置分类.
        /// </summary>
        internal static string page_detail_setCategory {
            get {
                return ResourceManager.GetString("page.detail.setCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应用.
        /// </summary>
        internal static string page_index_apps {
            get {
                return ResourceManager.GetString("page.index.apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更多.
        /// </summary>
        internal static string page_index_more {
            get {
                return ResourceManager.GetString("page.index.more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        internal static string page_index_refresh {
            get {
                return ResourceManager.GetString("page.index.refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 今日.
        /// </summary>
        internal static string page_index_time_today {
            get {
                return ResourceManager.GetString("page.index.time.today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本周.
        /// </summary>
        internal static string page_index_time_week {
            get {
                return ResourceManager.GetString("page.index.time.week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最为频繁.
        /// </summary>
        internal static string page_index_top {
            get {
                return ResourceManager.GetString("page.index.top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网站.
        /// </summary>
        internal static string page_index_websites {
            get {
                return ResourceManager.GetString("page.index.websites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tai 版本号.
        /// </summary>
        internal static string page_settings_about_version {
            get {
                return ResourceManager.GetString("page.settings.about.version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        internal static string page_settings_category_about {
            get {
                return ResourceManager.GetString("page.settings.category.about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关联.
        /// </summary>
        internal static string page_settings_category_associations {
            get {
                return ResourceManager.GetString("page.settings.category.associations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行为.
        /// </summary>
        internal static string page_settings_category_behavior {
            get {
                return ResourceManager.GetString("page.settings.category.behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据.
        /// </summary>
        internal static string page_settings_category_data {
            get {
                return ResourceManager.GetString("page.settings.category.data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 常规.
        /// </summary>
        internal static string page_settings_category_general {
            get {
                return ResourceManager.GetString("page.settings.category.general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法正确启动检查更新程序.
        /// </summary>
        internal static string page_settings_updaterError {
            get {
                return ResourceManager.GetString("page.settings.updaterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 升级程序似乎已被删除，请手动前往发布页查看新版本.
        /// </summary>
        internal static string page_settings_updaterRemoved {
            get {
                return ResourceManager.GetString("page.settings.updaterRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}小时.
        /// </summary>
        internal static string time_hours {
            get {
                return ResourceManager.GetString("time.hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}小时{1}分.
        /// </summary>
        internal static string time_hoursWithMinutes {
            get {
                return ResourceManager.GetString("time.hoursWithMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}分钟.
        /// </summary>
        internal static string time_minutes {
            get {
                return ResourceManager.GetString("time.minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}分钟{1}秒.
        /// </summary>
        internal static string time_minutesWithSeconds {
            get {
                return ResourceManager.GetString("time.minutesWithSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}秒.
        /// </summary>
        internal static string time_seconds {
            get {
                return ResourceManager.GetString("time.seconds", resourceCulture);
            }
        }
    }
}
