//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Resources.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored Apps.
        /// </summary>
        internal static string config_behaviorModel_group_ignoreProcess {
            get {
                return ResourceManager.GetString("config.behaviorModel.group.ignoreProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored URLs.
        /// </summary>
        internal static string config_behaviorModel_group_ignoreURL {
            get {
                return ResourceManager.GetString("config.behaviorModel.group.ignoreURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string config_behaviorModel_group_isSleepWatch {
            get {
                return ResourceManager.GetString("config.behaviorModel.group.isSleepWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Whitelist.
        /// </summary>
        internal static string config_behaviorModel_group_whiteList {
            get {
                return ResourceManager.GetString("config.behaviorModel.group.whiteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match by process name or regex. Regexes can match program paths..
        /// </summary>
        internal static string config_behaviorModel_ignoreProcessList_description {
            get {
                return ResourceManager.GetString("config.behaviorModel.ignoreProcessList.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored Apps.
        /// </summary>
        internal static string config_behaviorModel_ignoreProcessList_name {
            get {
                return ResourceManager.GetString("config.behaviorModel.ignoreProcessList.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process name (no &quot;.exe&quot; needed). Supports regular expressions.
        /// </summary>
        internal static string config_behaviorModel_ignoreProcessList_placeholder {
            get {
                return ResourceManager.GetString("config.behaviorModel.ignoreProcessList.placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter websites or links that should not be tracked..
        /// </summary>
        internal static string config_behaviorModel_ignoreURLList_description {
            get {
                return ResourceManager.GetString("config.behaviorModel.ignoreURLList.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored URLs.
        /// </summary>
        internal static string config_behaviorModel_ignoreURLList_name {
            get {
                return ResourceManager.GetString("config.behaviorModel.ignoreURLList.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports regexes.
        /// </summary>
        internal static string config_behaviorModel_ignoreURLList_placeholder {
            get {
                return ResourceManager.GetString("config.behaviorModel.ignoreURLList.placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically stops tracking when away from the computer. Takes effect after restarting the software. (Not recommended to disable).
        /// </summary>
        internal static string config_behaviorModel_isSleepWatch_description {
            get {
                return ResourceManager.GetString("config.behaviorModel.isSleepWatch.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep Monitoring.
        /// </summary>
        internal static string config_behaviorModel_isSleepWatch_name {
            get {
                return ResourceManager.GetString("config.behaviorModel.isSleepWatch.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only track applications in the whitelist.
        /// </summary>
        internal static string config_behaviorModel_isWhiteList_description {
            get {
                return ResourceManager.GetString("config.behaviorModel.isWhiteList.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Whitelist.
        /// </summary>
        internal static string config_behaviorModel_isWhiteList_name {
            get {
                return ResourceManager.GetString("config.behaviorModel.isWhiteList.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match by process name or regex. Regexes can match program paths..
        /// </summary>
        internal static string config_behaviorModel_processWhiteList_description {
            get {
                return ResourceManager.GetString("config.behaviorModel.processWhiteList.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Whitelist.
        /// </summary>
        internal static string config_behaviorModel_processWhiteList_name {
            get {
                return ResourceManager.GetString("config.behaviorModel.processWhiteList.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process name (no &quot;.exe&quot; needed). Supports regular expressions.
        /// </summary>
        internal static string config_behaviorModel_processWhiteList_placeholder {
            get {
                return ResourceManager.GetString("config.behaviorModel.processWhiteList.placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string config_general_group_appearance {
            get {
                return ResourceManager.GetString("config.general.group.appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string config_general_group_basic {
            get {
                return ResourceManager.GetString("config.general.group.basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        internal static string config_general_group_feature {
            get {
                return ResourceManager.GetString("config.general.group.feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview Page.
        /// </summary>
        internal static string config_general_group_overview {
            get {
                return ResourceManager.GetString("config.general.group.overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string config_general_indexPageFrequentUseNum_description {
            get {
                return ResourceManager.GetString("config.general.indexPageFrequentUseNum.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequent Items Count.
        /// </summary>
        internal static string config_general_indexPageFrequentUseNum_name {
            get {
                return ResourceManager.GetString("config.general.indexPageFrequentUseNum.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1|2|3|4|5|6|7|8|9|10.
        /// </summary>
        internal static string config_general_indexPageFrequentUseNum_options {
            get {
                return ResourceManager.GetString("config.general.indexPageFrequentUseNum.options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string config_general_indexPageMoreNum_description {
            get {
                return ResourceManager.GetString("config.general.indexPageMoreNum.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Items Count.
        /// </summary>
        internal static string config_general_indexPageMoreNum_name {
            get {
                return ResourceManager.GetString("config.general.indexPageMoreNum.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20.
        /// </summary>
        internal static string config_general_indexPageMoreNum_options {
            get {
                return ResourceManager.GetString("config.general.indexPageMoreNum.options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep the current window size instead of using the default.
        /// </summary>
        internal static string config_general_isSaveWindowSize_description {
            get {
                return ResourceManager.GetString("config.general.isSaveWindowSize.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Window Size.
        /// </summary>
        internal static string config_general_isSaveWindowSize_name {
            get {
                return ResourceManager.GetString("config.general.isSaveWindowSize.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically run Tai when the computer starts.
        /// </summary>
        internal static string config_general_isStartAtBoot_description {
            get {
                return ResourceManager.GetString("config.general.isStartAtBoot.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart.
        /// </summary>
        internal static string config_general_isStartAtBoot_name {
            get {
                return ResourceManager.GetString("config.general.isStartAtBoot.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option has no effect when auto-starting with the system.
        /// </summary>
        internal static string config_general_isStartupShowMainWindow_description {
            get {
                return ResourceManager.GetString("config.general.isStartupShowMainWindow.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Main Window on Startup.
        /// </summary>
        internal static string config_general_isStartupShowMainWindow_name {
            get {
                return ResourceManager.GetString("config.general.isStartupShowMainWindow.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track website visits in supported browsers: Google Chrome, MS Edge, or any browser supporting Chrome extensions. Go to “About &gt; Browser Tracking Plugin” for installation and usage instructions..
        /// </summary>
        internal static string config_general_isWebEnabled_description {
            get {
                return ResourceManager.GetString("config.general.isWebEnabled.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Activity Tracking.
        /// </summary>
        internal static string config_general_isWebEnabled_name {
            get {
                return ResourceManager.GetString("config.general.isWebEnabled.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which page is shown when the app is opened.
        /// </summary>
        internal static string config_general_startPage_description {
            get {
                return ResourceManager.GetString("config.general.startPage.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Page.
        /// </summary>
        internal static string config_general_startPage_name {
            get {
                return ResourceManager.GetString("config.general.startPage.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview|Statistics|Details|Categories.
        /// </summary>
        internal static string config_general_startPage_options {
            get {
                return ResourceManager.GetString("config.general.startPage.options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose between light or dark mode.
        /// </summary>
        internal static string config_general_theme_description {
            get {
                return ResourceManager.GetString("config.general.theme.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Mode.
        /// </summary>
        internal static string config_general_theme_name {
            get {
                return ResourceManager.GetString("config.general.theme.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light|Dark.
        /// </summary>
        internal static string config_general_theme_options {
            get {
                return ResourceManager.GetString("config.general.theme.options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string config_general_themeColor_description {
            get {
                return ResourceManager.GetString("config.general.themeColor.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Color.
        /// </summary>
        internal static string config_general_themeColor_name {
            get {
                return ResourceManager.GetString("config.general.themeColor.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置一个名称用于识别该关联.
        /// </summary>
        internal static string config_linkMode_name_description {
            get {
                return ResourceManager.GetString("config.linkMode.name.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string config_linkMode_name_name {
            get {
                return ResourceManager.GetString("config.linkMode.name.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将需要关联的进程名称（不带.exe）添加到此，至少两个。.
        /// </summary>
        internal static string config_linkMode_processList_description {
            get {
                return ResourceManager.GetString("config.linkMode.processList.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关联进程.
        /// </summary>
        internal static string config_linkMode_processList_name {
            get {
                return ResourceManager.GetString("config.linkMode.processList.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string main_details {
            get {
                return ResourceManager.GetString("main.details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string main_overview {
            get {
                return ResourceManager.GetString("main.overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string main_statistics {
            get {
                return ResourceManager.GetString("main.statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} added to whitelist.
        /// </summary>
        internal static string page_detail_addedToWhitelist {
            get {
                return ResourceManager.GetString("page.detail.addedToWhitelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to whitelist.
        /// </summary>
        internal static string page_detail_addToWhitelist {
            get {
                return ResourceManager.GetString("page.detail.addToWhitelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear statistics.
        /// </summary>
        internal static string page_detail_clearAppData {
            get {
                return ResourceManager.GetString("page.detail.clearAppData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy path.
        /// </summary>
        internal static string page_detail_copyPath {
            get {
                return ResourceManager.GetString("page.detail.copyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy name.
        /// </summary>
        internal static string page_detail_copyProcessname {
            get {
                return ResourceManager.GetString("page.detail.copyProcessname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit alias.
        /// </summary>
        internal static string page_detail_editAlias {
            get {
                return ResourceManager.GetString("page.detail.editAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open app.
        /// </summary>
        internal static string page_detail_launchApp {
            get {
                return ResourceManager.GetString("page.detail.launchApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        internal static string page_detail_openDir {
            get {
                return ResourceManager.GetString("page.detail.openDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string page_detail_reload {
            get {
                return ResourceManager.GetString("page.detail.reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} removed from whitelist.
        /// </summary>
        internal static string page_detail_removedFromWhitelist {
            get {
                return ResourceManager.GetString("page.detail.removedFromWhitelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from whitelist.
        /// </summary>
        internal static string page_detail_removeFromWhitelist {
            get {
                return ResourceManager.GetString("page.detail.removeFromWhitelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set category.
        /// </summary>
        internal static string page_detail_setCategory {
            get {
                return ResourceManager.GetString("page.detail.setCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tai Version:.
        /// </summary>
        internal static string page_settings_about_version {
            get {
                return ResourceManager.GetString("page.settings.about.version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string page_settings_category_about {
            get {
                return ResourceManager.GetString("page.settings.category.about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associations.
        /// </summary>
        internal static string page_settings_category_associations {
            get {
                return ResourceManager.GetString("page.settings.category.associations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        internal static string page_settings_category_behavior {
            get {
                return ResourceManager.GetString("page.settings.category.behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string page_settings_category_data {
            get {
                return ResourceManager.GetString("page.settings.category.data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string page_settings_category_general {
            get {
                return ResourceManager.GetString("page.settings.category.general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error executing the updater!.
        /// </summary>
        internal static string page_settings_updaterError {
            get {
                return ResourceManager.GetString("page.settings.updaterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems like the updater was removed. Please download new versions manually on the release page..
        /// </summary>
        internal static string page_settings_updaterRemoved {
            get {
                return ResourceManager.GetString("page.settings.updaterRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}h.
        /// </summary>
        internal static string time_hours {
            get {
                return ResourceManager.GetString("time.hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}h {1}min.
        /// </summary>
        internal static string time_hoursWithMinutes {
            get {
                return ResourceManager.GetString("time.hoursWithMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}min.
        /// </summary>
        internal static string time_minutes {
            get {
                return ResourceManager.GetString("time.minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}min {1}sec.
        /// </summary>
        internal static string time_minutesWithSeconds {
            get {
                return ResourceManager.GetString("time.minutesWithSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}sec.
        /// </summary>
        internal static string time_seconds {
            get {
                return ResourceManager.GetString("time.seconds", resourceCulture);
            }
        }
    }
}
